In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-06-24 20:42:49.854230: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
# define the vocab size 
voc_size = 10000


In [4]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [5]:
one_hot_repr

[[6176, 7811, 9727, 5132],
 [6176, 7811, 9727, 3211],
 [6176, 4251, 9727, 2226],
 [4216, 8133, 1948, 2719, 3443],
 [4216, 8133, 1948, 2719, 9181],
 [7172, 6176, 6246, 9727, 3466],
 [2069, 4207, 1782, 2719]]

the output above shows index number where these words will be present in vocab,
if we expand each word all other index will be zero and only this index will be one

In [6]:
#word embedding representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

all sentences must be of same length, so that is why we use pad_sequence
The vectors which are not of 8 length, 0s will be added to make them 8 characters long


In [9]:
#setting max sentence length 
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
#padding = pre means 0s will be added in start to make vector length = 8
# we can also use 'post'


In [10]:
print(embedded_docs)

[[   0    0    0    0 6176 7811 9727 5132]
 [   0    0    0    0 6176 7811 9727 3211]
 [   0    0    0    0 6176 4251 9727 2226]
 [   0    0    0 4216 8133 1948 2719 3443]
 [   0    0    0 4216 8133 1948 2719 9181]
 [   0    0    0 7172 6176 6246 9727 3466]
 [   0    0    0    0 2069 4207 1782 2719]]


In [11]:
# feature representation
dim = 10


In [17]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse') #mse is loss function


In [18]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step


array([[[ 0.04786981,  0.03156117, -0.01551614, -0.0284677 ,
         -0.01947418, -0.00749779, -0.00991269, -0.00239712,
         -0.01100863,  0.03812358],
        [ 0.04786981,  0.03156117, -0.01551614, -0.0284677 ,
         -0.01947418, -0.00749779, -0.00991269, -0.00239712,
         -0.01100863,  0.03812358],
        [ 0.04786981,  0.03156117, -0.01551614, -0.0284677 ,
         -0.01947418, -0.00749779, -0.00991269, -0.00239712,
         -0.01100863,  0.03812358],
        [ 0.04786981,  0.03156117, -0.01551614, -0.0284677 ,
         -0.01947418, -0.00749779, -0.00991269, -0.00239712,
         -0.01100863,  0.03812358],
        [-0.04076387, -0.00514321, -0.04114897,  0.00667452,
         -0.02956598, -0.04148762,  0.02810887,  0.00484481,
         -0.02571728,  0.04246445],
        [ 0.0439103 ,  0.04069182,  0.04443988, -0.00404697,
          0.01918149, -0.04777604,  0.04908125, -0.00182799,
         -0.02671238, -0.04577873],
        [-0.04989668, -0.04143461,  0.0194735 ,  0.0